name: Build CUDA Wheel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y g++-12 ninja-build cmake python3-pip
          python3 -m pip install --upgrade pip

      - name: Build CUDA wheel
        run: |
          export CXX=/usr/bin/g++-12
          CMAKE_ARGS="-DLLAMA_CUDA=on -DCMAKE_CUDA_HOST_COMPILER=/usr/bin/g++-12 -DCMAKE_CUDA_ARCHITECTURES=89" \
          pip wheel . --no-deps --wheel-dir dist

      - name: Upload CUDA wheel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: llama_cpp_cuda_wheel
          path: dist/*.whl

